### ISSUE TITLE
length-prefixed-stream

### ISSUE THREAD

**Issue by mafintosh** [mapbox/pbf-split#2]
FYI, https://github.com/mafintosh/length-prefixed-stream does this as well (with both an encoder/decoder) and is pretty well tested

**Comment by mourner** [comment]
Oh shit, I searched for existing streams but missed your repo completely. :( Sorry. At least I got to learn something new about streams while writing this.

I wonder how much our decoding approaches differ...

**Comment by mourner** [comment]
Mine is also clearly inferior in performance — on a test 12Mb pbf, it takes 140ms to stream with my module and 90ms with yours. Glad I didn't publish it to NPM yet. :( Will archive the repo then.
